version: "2"


services:
  aaas-app-zhongzhengapi:
    image: aaas-app-zhongzhengapi:latest
    labels:
      - "aaas-app-zhongzhengapi"
    ports:
      - "10160:10170"
      - "10161:10171"
    environment:
      - SPRING_PROFILES_ACTIVE=k8s
      - _JAVA_OPTIONS=-Xmx256m
      - TZ=Asia/Shanghai
      
      
