package com.shellshellfish.aaas.finance.trade.pay.model;

public class ConfirmResult {
    private String tradeacco;
    private String fundacco;
    private String fundcode;
    private String fundname;
    private String callingcode;
    private String branchno;
    private String applyserial;
    private String sharetype;
    private String applydate;
    private String applytime;
    private String applyshare;
    private String applysum;
    private String balancecoin;
    private String targetfundcode;
    private String targetfundname;
    private String targetsharetype;
    private String oppfundcode;
    private String oppsaler;
    private String opptrusteebranch;
    private String mintredeem;
    private String commisiondiscount;
    private String melonmethod;
    private String freezemethod;
    private String originalapplyserial;
    private String confirmflag;
    private String confirmstat;
    private String capitalmode;
    private String comefrom;
    private String kkstat;
    private String enddiscount;
    private String otherdiscount;
    private String oriapplydate;
    private String trademethod;
    private String accepttime;
    private String riskmatch;
    private String bankacco;
    private String bankname;
    private String businflagStr;
    private String occurbankacco;
    private String bankSerial;
    private String outsideorderno;
    private String tradeconfirmshare;
    private String tradeconfirmsum;
    private String xyh;
    private String poundage;
    private String fixflag;

}
