server:
  port: 10100
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data: debug
spring:
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
    username: ssf
    password: shellshellfish
    host: 192.168.1.249
    port: 5772
    virtual-host: aaas
    topicOrder: shellshellfish.order

  data:
    mongodb:
      host: 192.168.1.10
      port: 27017
      database: zhongzheng
  redis:
    host: 192.168.1.10
    port: 6379
    password: redis123
    timeout: 1800000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 1800000ms
        max-idle: 8
        min-idle: 0


datasource:
  aaasapp:
    url: jdbc:mysql://192.168.1.10:3306/ssftrdorder?useUnicode=true&connectionCollation=utf8_general_ci&characterSetResults=utf8&characterEncoding=utf-8
    username: sa
    password: N4eTVr89lX9BaPcx
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: ssftrdorder
    maxPoolSize: 20
    hibernate:
      connection:
        useUnicode: true
        characterEncoding: UTF-8
      jdbc:
        batch_size: 50
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL57Dialect
      id.new_generator_mappings: false


grpc:
  finance_prod_client:
    host: localhost
    port: 10021
  pay_client:
    host: localhost
    port: 10111
  datacollection_client:
    host: localhost
    port: 10091
  order_server:
    host: localhost
    port: 10101
  userinfo_client:
    host: localhost
    port: 10061
  zhongzhengapi_client:
    host: localhost
    port: 10171


org:
  quartz:
    jobStore:
        class: org.quartz.simpl.RAMJobStore
        misfireThreshold: 60000
    threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 2
        threadsInheritContextClassLoaderOfInitializingThread: true
using:
  spring:
    schedulerFactory: true
cron:
  frequency:
    #每天5 18 点开始
    jobCheckOrderWithPay: 0 0 0/3 1/1 * ? *

management:
  endpoints:
    web:
      base-path: /
