zuul:
  routes:
    api-mid:
      path: /phoneapi-ssf/**
      url: http://localhost:10130/phoneapi-ssf
    apii-mid:
      path: /phoneapii-ssf/**
      url: http://localhost:10140/phoneapii-ssf
    userinfo:
      path: /api/f/SHT/temp-11-15/aaas/aaas-api-gateway/userinfo/**
      url: http://localhost:10060/api/userinfo/
    userlogin:
      path: /api/useraccount/**
      url: http://localhost:10070/api/useraccount/
    userinfo-swagger:
      path: /api/userinfo/swagger-ui.html
      url: http://localhost:10060/swagger-ui.html#
    riskassessments:
      path: /api/riskassessments/**
      url: http://localhost:10050/api/riskassessments/
    userlogin-swagger:
      path: /api/useraccount/swagger-ui.html/**
      url: http://localhost:10070/swagger-ui.html
    riskassessments-swagger:
      path: /api/riskassessments/swagger-ui.html/**
      url: http://localhost:10050/swagger-ui.html/
    datamanager:
      path: /api/datamanager/**
      url: http://localhost:10030//api/datamanager
#    accounts:
#      path: /v1/accounts/**
#      url: http://localhost:8080/api/accounts
#    bankaccounts:
#      path: /v1/bankaccounts/**
#      url: forward:/api/bankaccounts/**
    auth:
      path: /v1/auth/**
      sensitiveHeaders: Cookie,Set-Cookie
      url: http://localhost:10070/auth

ribbon:
  eureka:
    enabled: false

server:
  port: 10040
grpc:
  host: localhost
  port: 10041
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:10070/auth/user

shellshellfish:
  ignoredWhitelist:
    - /api/datamanager/**
    - /api/userinfo/**
    - /api/useraccount/**
    - /api/riskassessments/**
    - /v1/auth/oauth/token
    - /v1/api/bankaccounts/**
    - /phoneapi-ssf/**
    - /phoneapii-ssf/**
    - /heartbeat/

management:
  endpoints:
    web:
      base-path: /