---
server:
  port: 10030
  contextPath: /
---
spring:
#  profiles: local, default
datasource:
  aaasapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
  
---
spring:
#  profiles: k8s
  data:
      mongodb:
        database: funds
        host: external-mongo-service
        port: 27017
  http:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
datasource:
  aaasapp:
    url: jdbc:mysql://external-mysql-service:3306/ssftrdorder?useUnicode=true&characterEncoding=utf-8
    username: sa
   # password: 1qaz@WSX
    password: 1rIQ9wi!@g3P$Qh*
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect
shellshellfish:
  asset-alloction-url: "http://localhost:10020"

cron:
  frequency:
    #Seconds	Minutes	Hours	Day Of Month	Month	Day Of Week	Year
    # 	Every 3 hours
    jobCheckFunds: 0 0 0/3 1/1 * ? *
using:
  spring:
    schedulerFactory: true
