server:
  port: 10020

mybatis:
    config-locations: classpath:mybatis/mybatis-config.xml
    mapper-locations: classpath:mybatis/mapper/*.xml
spring:
#  datasource:
#      driverClassName: com.mysql.jdbc.Driver
#      password: 1rIQ9wi!@g3P$Qh*
#      url: jdbc:mysql://localhost:3306/choice?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
#      username: ssf08
#        password: uCIPzdEJzbeoFAMj
#        url: jdbc:mysql://172.16.128.72:3306/choicecopy?useUnicode=true&characterEncoding=utf-8
#        username: ssf09
  jpa:
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: funds
      host: 192.168.1.249
      port: 30005
      collection: portfolio_yield_all

datasource:
  sampleapp:
    url: jdbc:mysql://192.168.1.249:30006/choice?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: ssf08
    password: 1rIQ9wi!@g3P$Qh*
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema: ssfuser
    maxPoolSize: 20
    hibernate:
      connection:
        useUnicode: true
        characterEncoding: UTF-8
      jdbc:
        batch_size: 50
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

grpc:
  host: localhost
  port: 10021
  daily-fund-client:
    host: localhost
    port: 10091

application:
    swagger:
        title: SSF Platform API
        description: Shell shell fish API documentation
        version: 0.1.X
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl: